version: '3.8'
services:
  # Servicio de backend en .NET
  backend:
    build:
      context: ./visualNetworkAPI
      dockerfile: Dockerfile
    container_name: visualnetwork-api
    restart: always
    ports:
      - "5295:80"
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ConnectionStrings__SQLServer: Server=db;Database=visualNetWork;User Id=sa;Password=YourStrong@Passw0rd;TrustServerCertificate=True;
    volumes:
      - ./uploaded_files:/App/wwwroot
    depends_on:
      - db
    networks:
      - visualnetwork

  # Servicio de Nginx para servir archivos estáticos
  nginx:
    image: nginx:latest
    container_name: visualnetwork-nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./uploaded_files:/var/www/files
    depends_on:
      - backend
    networks:
      - visualnetwork

  # Servicio de base de datos SQL Server
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: visualnetwork-db
    restart: always
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "YourStrong@Passw0rd"
      MSSQL_PID: "Express"
    ports:
      - "1433:1433"
    volumes:
      - dbdata:/var/opt/mssql
    networks:
      - visualnetwork

networks:
  visualnetwork:
    driver: bridge

volumes:
  dbdata: